# Generated by Django 5.0.7 on 2024-08-04 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.AddField(
            model_name="client",
            name="tenant_name",
            field=models.CharField(default="public", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="client",
            name="tenant_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="client",
            name="domain_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
